package CommonFunctionLibrary;

import java.util.List;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.Reporter;

import Utilities.PropertyFileUtil;

public class CommonFunction {

	static WebDriver driver;
	static WebDriverWait wait;
	public static String actEmpId ="";
	public static WebDriver launchBrowser() throws Throwable 
	{
	
		if(PropertyFileUtil.getKeyValue("browser").equalsIgnoreCase("chrome"))
		{
		System.setProperty("webdriver.chrome.driver", "C:\\OJTProjectTesting\\OrangeHRMDemo\\CommonDrivers\\chromedriver.exe");
		driver=new ChromeDriver();
		
		}
		else
		System.out.println("browser not found");
		driver.manage().window().maximize();
		
	 return driver;
	}
	
	
	public static void lanuchApplication(WebDriver driver) throws Throwable
	{
		driver.get(PropertyFileUtil.getKeyValue("url"));
		
	}
	
	public static void waitForElement(WebDriver driver,String LocatorType,String LocatorValue,String TestData)
	{
		int waittime= Integer.valueOf(TestData);
		wait= new WebDriverWait(driver,waittime);
		if(LocatorType.equalsIgnoreCase("id"))
		{
			wait.until(ExpectedConditions.visibilityOfElementLocated(By.id(LocatorValue)));
		}
		else if(LocatorType.equalsIgnoreCase("name"))
		{
			
			wait.until(ExpectedConditions.elementToBeClickable(By.name(LocatorValue)));
		}
		
		else if(LocatorType.equalsIgnoreCase("xpath"))
		{
			
			//wait.until(ExpectedConditions.elementToBeClickable(By.xpath(LocatorValue)));
			wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(LocatorValue)));
			System.out.println("wait done");
			
		}
	 }
	
	public static void typeAction(WebDriver driver,String LocatorType, String LocatorValue, String TestData )
	{
		//wait=new WebDriverWait(driver,)
		if(LocatorType.equalsIgnoreCase("id"))
		{
			driver.findElement(By.id(LocatorValue)).clear();
			driver.findElement(By.id(LocatorValue)).sendKeys(TestData);
		}
		else if(LocatorType.equalsIgnoreCase("name"))
		{
			driver.findElement(By.name(LocatorValue)).clear();
			driver.findElement(By.name(LocatorValue)).sendKeys(TestData);
		}
	}
	
	public static void clickAction(WebDriver driver,String LocatorType,String LocatorValue)
	{
		 if(LocatorType.equalsIgnoreCase("id"))
		 {
			driver.findElement(By.id(LocatorValue)).click();
		 }
		  else if(LocatorType.equalsIgnoreCase("name"))
		 {
			driver.findElement(By.name(LocatorValue)).click();
		 }
		 
		  else if(LocatorType.equalsIgnoreCase("xpath"))
		 {
			 driver.findElement(By.xpath(LocatorValue)).click();
			 
		 }
	}
	
	
	  public static void mouseHover(WebDriver driver ,String LocatorType,String LocatorValue)
	  {
		  Actions action= new Actions(driver);
		  if(LocatorType.equalsIgnoreCase("xpath"))
		  {
			action.moveToElement(driver.findElement(By.xpath(LocatorValue))).build().perform();
		  }
		  
		  else if(LocatorType.equalsIgnoreCase("id"))
		  {
		    action.moveToElement(driver.findElement(By.id(LocatorValue))).build().perform();
		  }
		
	 }
	
	   public static void captureData(WebDriver driver,String LocatorType,String LocatorValue)
	   {
		   if(LocatorType.equalsIgnoreCase("id"))
		   actEmpId= driver.findElement(By.id(LocatorValue)).getAttribute("Value");
		   
		   else if(LocatorType.equalsIgnoreCase("xpath"))
		   {
		   actEmpId= driver.findElement(By.xpath(LocatorValue))  .getAttribute("Value");
		 
		   }
		   
			   
	   }
	   
	   public static void validateEmployeetable(WebDriver driver,String LocatorType,String LocatorValue,String testData) throws Throwable
	   {
		   String empId="";
		  int column=     Integer.parseInt(testData);
		   System.out.println("validate actual employee Id " +actEmpId);
		   driver.findElement(By.id("empsearch_id")).sendKeys(actEmpId);  //enter autogenerated emp id
		   Thread.sleep(5000);
		   driver.findElement(By.id("searchBtn")).click();
		   Thread.sleep(4000);
		   WebElement table= driver.findElement(By.xpath("//table[@id='resultTable']/tbody"));
		   List<WebElement> rows=table.findElements(By.tagName("tr"));
		   for(int i=1;i<=rows.size();i++)
		   {
			 
			  empId=driver.findElement(By.xpath("//table[@id='resultTable']/tbody/tr["+i+"]/td["+column+"]/a")).getText();
			  Assert.assertEquals(actEmpId, empId,"not matched");
			  Reporter.log(actEmpId+" "+empId,true);
			  break;
			   
		   }
		 }
	   
	   public static void closeBrowser(WebDriver driver)
	   {
		   driver.close(); 
	   }
	 }
